name: Build And Release
on:
  release:
    types: [created]

jobs:
  release-content:
    name: Release Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read config
        id: read_config
        run: |
          pack_version=$(jq -r '.pack_version' ./configs/version.json)
          version=$(jq -r '.version' ./configs/version.json)
          echo "pack_version=$pack_version" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Go to resource pack directory
        run: cd resourcepack

      - name: Zip artifact for deployment
        run: zip ThaiFontFix.zip ./ -r

      - name: Upload Assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ThaiFontFix.zip
          asset_name: ThaiFontFix-${{ steps.read_config.outputs.version }}-${{ steps.read_config.outputs.pack_version }}.zip
          asset_content_type: application/zip
      
