name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Building Resource Pack
        uses: actions/upload-artifact@v3
        with:
          name: ThaiFontFix
          path: ./resourcepack
  release-content:
    name: Release Resource Pack
    runs-on: ubuntu-latest
    # needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download Artifacts
        id: download_artifacts
        uses: actions/download-artifact@v2
        with:
          name: ThaiFontFix
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: true
      - name: Upload Assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./ThaiFontFix.zip
          asset_name: ThaiFontFix-${{ github.ref_name }}.zip
          asset_content_type: application/zip
