name: Build and Release
on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Building Resource Pack
        uses: actions/upload-artifact@v3
        with:
          name: ThaiFontFix
          path: ./resourcepack  
