name: Build And Release
on:
  release: 
    types: [created]

jobs:
  release-content:
    name: Release Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read config
        id: read_config
        run: echo ::set-output name=version::$(cat ./configs/version.json | jq -r '.version')

      - name: Zip artifact for deployment
        run: zip ThaiFontFix.zip ./resourcepack -r

      - name: Upload Assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ThaiFontFix.zip
          asset_name: ThaiFontFix-${{ fromJson(steps.read_config.outputs.version).pack_version }}.zip
          asset_content_type: application/zip
